### ISSUE TITLE
View "visible: count;" doesn't work

### ISSUE THREAD

**Issue by comrat** [pureqml/qmlcore#117]
If view visibility depends on its 'count' property it will be invisible all the time.
Simple example to reproduce:

		ListView {
			id: testView;
			width: 100;
			height: 100%;
			spacing: 10;
			visible: count;
			model: ListModel { }
			delegate: Rectangle {
				width: 100;
				height: 50;
				color: "#f00";
			}

			onCountChanged: { log("onCountChanged:", value) }

			onCompleted: {
				var data = [{ text: "delegate1" }, { text: "delegate1" }]
				this.model.append(data)
			}
		}

But when you try do handle it via model it works fine:
`			visible: testModel.count;
			model: ListModel { id: testModel; }`

**Comment by whoozle** [comment]
fixed in 74a5ee422a589b95e4e89fa85765d52e059919d8
