### ISSUE TITLE
Functions in property

### ISSUE THREAD

**Issue by ghost** [pureqml/qmlcore#138]
```
property string str: "Something".toUpperCase()
property var var1: something(width)
function something(width) { return this.width * this.height + 10  }
```
@whoozle

**Comment by whoozle** [comment]
sorry for the late reply, adding this will be really problematic as we're parsing property expressions to get dependencies at the compile time, not in runtime, as qml does. 
Potentially I could add it, but it won't track dependencies properly, I'm not sure if it's what you want. 

Btw, your example is pretty trivial, and you can rewrite it as ```var1: width * height + 10;```

**Comment by Lwing** [comment]
Maybe the function I also called somewhere else? Though, personally, I've never ever needed to call function as property. Usually I'd use a Binding instead

**Comment by whoozle** [comment]
If it's common code, maybe refactor it to onChanged { this.func() }. We also support multiple handlers, e.g.
```
onXChanged, onYChanged: { ... } 
```
And it's re-using code there, so no duplication should happen

**Comment by whoozle** [comment]
Supported in the latest qmlcore
