### ISSUE TITLE
an unknow error

### ISSUE THREAD

**Issue by t2dk49580** [pureqml/qmlcore#144]
src/P0.qml:30:5: error: Expected "}" (at char 793), (line:30, col:5)
    Rectangle {

I do not understand this error

in QtCreator is all right

**Comment by t2dk49580** [comment]
[P0.zip](https://github.com/pureqml/qmlcore/files/2611953/P0.zip)

**Comment by t2dk49580** [comment]
pls help...

**Comment by whoozle** [comment]
pyparsing could be better in error reporting, really, the problem fragment is:
```
                    SequentialAnimation {
                        id: anibuy;
                        running: true;
                        NumberAnimation { target: image21; property: "rotation"; to: 10; duration: 100 }
                        NumberAnimation { target: image21; property: "rotation"; to: -10; duration: 100 }
                        NumberAnimation { target: image21; property: "rotation"; to: 10; duration: 100 }
                        NumberAnimation { target: image21; property: "rotation"; to: -10; duration: 100 }
                        NumberAnimation { target: image21; property: "rotation"; to: 0; duration: 100 }
                        NumberAnimation { target: image21; property: "rotation"; to: 0; duration: 500 }
                    }
```

Please add semicolons to the end of each line and it compiles OK
```
                        NumberAnimation { target: image21; property: "rotation"; to: 0; duration: 100; } //<- note semicolon
                        NumberAnimation { target: image21; property: "rotation"; to: 0; duration: 500; }
```

I'm not sure if we have sequential animation, @comrat @vkrv ?

**Comment by t2dk49580** [comment]
what to replace for SequentialAnimation ?

**Comment by whoozle** [comment]
I'm gonna add them soon, probably today! You can start without them, I'll let you know when I'm done

**Comment by t2dk49580** [comment]
wow! That is great!

**Comment by t2dk49580** [comment]
error: component SequentialAnimation was not found

probably today!.......................... :(

**Comment by whoozle** [comment]
I'm really sorry about long delay, I've just implemented component you asked for. Please pull the latest changes, it should be there. 

Fully functional example is available at:
https://github.com/pureqml/parus/blob/master/src/SequentialAnimationTest.qml

SequentialAnimation is pretty basic, it has only 'running' property for now. 

Don't hesitate opening new feature requests and/or contacting us in case you need something.

**Comment by t2dk49580** [comment]
thanks!
