### ISSUE TITLE
Сanvas element is not working inside Item 

### ISSUE THREAD

**Issue by SmartPtz** [pureqml/qmlcore#148]
my QML source

`Item {
    width: 400;
    height: 400;
                Rectangle{
                width: 300;
                height:300;
                color: "gray";

                Canvas {
                        id: canvas;
                        width: 200;
                        height: 200;

                        onPaint: {
                        var ctx = getContext("2d");
                        context.beginPath();
                        context.strokeStyle = "lime green";
                        context.font = "20px sans-serif";
                        context.text("Hello!", width/2, 50);
                        context.stroke();}
                        }

                }
    }`

**Comment by whoozle** [comment]
web.Canvas is a simple wrapper around html canvas, there's no paint signal. 
Try placing your code in 
```
onCompleted: {
  var ctx = this.getContext("2d");
  …
}
```
