### ISSUE TITLE
 failed at step 3 with the simple-how-to

### ISSUE THREAD

**Issue by redstoneleo** [pureqml/qmlcore#162]
I am a newbie on the domain of using QML in browser , I followed the [Simple how-to](https://github.com/pureqml/qmlcore#simple-how-to) and want to make the first example from https://doc.qt.io/qt-5/qmlfirststeps.html#handling-user-input to work in the browser with qmlcore, but failed at step 3 with 

```
C:\Users\i\Downloads\LiuYi10000\qmlcore-master>build --boilerplate
'build' is not recognized as an internal or external command operable program or batch file

C:\Users\i\Downloads\LiuYi10000\qmlcore-master>
```
So what should I do ?

**Comment by comrat** [comment]
Hello!
It looks like you trying to run `build` script on windows but you can't run python script explicitly there.
You can try [.exe build file](https://github.com/pureqml/qmlcore/releases)

**Comment by redstoneleo** [comment]
Thank you ! I followed your instruction and I changed the code in `src\app.qml` as following :
```
Rectangle {
    width: 200
    height: 100
    color: "red"

    Text {
        anchors.centerIn: parent
        text: "Hello, World!"
    }

    TapHandler {
        onTapped: parent.color = "blue"
    }
}
```
then I got 
```
C:\Users\i\Downloads\qmlcore>build
building app for web...
parsing src\app.qml ... src.app
src\app.qml:2:5: error: Expected "}" (at char 16), (line:2, col:5)
    width: 200

C:\Users\i\Downloads\qmlcore>

```

So any way to fix the problem ?

**Comment by comrat** [comment]
You've forget semicolon `;` for each line.
Pureqml doesn't support semicolon ignoring logic right now.

**Comment by redstoneleo** [comment]
Thanks! I added semicolon, so changed to 
```
Rectangle {
    width: 200;
    height: 100;
    color: "red";

    Text {
        anchors.centerIn: parent;
        text: "Hello, World!";
    }

    TapHandler {
        onTapped: parent.color = "blue";
    }
}
```
but still got 
```
C:\Users\i\Downloads\qmlcore>build
building app for web...
parsing src\app.qml ... src.app
src\app.qml:11:5: error: Expected "}" (at char 151), (line:11, col:5)
    TapHandler {

C:\Users\i\Downloads\qmlcore>
```

**Comment by comrat** [comment]
You need to wrap code in `{}` here
```
        onTapped: parent.color = "blue";
```

**Comment by redstoneleo** [comment]
You mean changed to this?
```
Rectangle {
    width: 200;
    height: 100;
    color: "red";

    Text {
        anchors.centerIn: parent;
        text: "Hello, World!";
    }

    TapHandler {
        onTapped: {parent.color = "blue";}
    }
}
```
then I got
```
C:\Users\i\Downloads\qmlcore>build
building app for web...
parsing src\app.qml ... src.app
error: component TapHandler was not found

C:\Users\i\Downloads\qmlcore>

```

**Comment by comrat** [comment]
What is TapHandler? We havn't any control with such name.

**Comment by redstoneleo** [comment]
https://doc.qt.io/qt-5/qml-qtquick-taphandler.html

**Comment by redstoneleo** [comment]
Thanks ! Honestly speaking , I don't know whether it is necessary to implement TapHandler and the related stuff in pureqml , perhaps this post might help you make the decision .
https://www.qt.io/blog/2017/11/23/say-hello-qt-quick-pointer-handlers

**Comment by whoozle** [comment]
Thanks for suggestion, I think this is really close to what we have at the moment.
