### ISSUE TITLE
How to create component dynamically

### ISSUE THREAD

**Issue by tim37021** [pureqml/qmlcore#165]
Hi, what's the proper way to create component dynamically

I've tried:
```javascript
const x = new $ui.MyWidget(parent);
parent.addChild(x);
```

but x has no children and properties and their bindings, if but it seems it's not suggested to call $c $s manually.

**Comment by whoozle** [comment]
Hi
Thanks for reaching us out :)

There's a few ways of doing this, and instantiation is the most complex of them. :)

The easiest way of creating components dynamically is `Loader`:
https://pureqml.com/docs/core/Loader.html

If you really want to create components dynamically, you can use the following snippet from Loader

```javascript
		var item = new <COMPONENT>(PARENT);
		item.__init(); //this will call all creation phases ($c and $s)
		this._context.scheduleComplete() //run onCompleted, you can call it just once after all components have been created
		this._updateVisibilityForChild(this.item, this.recursiveVisible); //this is needed for visible/recursiveVisible to work
		this._tryFocus(); //this will set focus if needed
```

__init is a shortcut for single component creation. If you want to create more than one component, you have to do it in  more phases

for all components you have to call
1. ctor (with proper parent)
2. `$c` (this will add ids)
3. `$s` (this will install all handlers and schedule async handlers)
4. `this._updateVisibilityForChild(this.item, this.recursiveVisible)`
5. `this._tryFocus()`

after that you have to call `this._context.scheduleComplete()`

addChild is not strictly needed, only if you want the object appear among `.children`

**Comment by tim37021** [comment]
Thanks for quick support, we got it.
I want to continuously add new component, loader is not really for this case.

**Comment by whoozle** [comment]
have you managed?

**Comment by tim37021** [comment]
Yes I've successfully implemented a trello like card system which's involved data reordering..

**Comment by tim37021** [comment]
![image](https://user-images.githubusercontent.com/5507113/71777060-03b63100-2fd6-11ea-9651-ac07302445b5.png)
![image](https://user-images.githubusercontent.com/5507113/71777064-12044d00-2fd6-11ea-865b-9f283112bf8c.png)

**Comment by whoozle** [comment]
awesome! thanks!

**Comment by whoozle** [comment]
starting with 07098447450bbb49ed1bc8c3880ef49fce699bb4, it's possible to just 

```javascript
var foo = new Foo(parent)
$core.core.createObject(foo)
```
