### ISSUE TITLE
Row's width calculation for Text component is incorrect.

### ISSUE THREAD

**Issue by paiext** [pureqml/qmlcore#171]
After running the example below, when checking by DevTool, myText has a width of 38. MyRow has a width of 37. myText and MyRow's width should be the same.

```
    Row {    
      id: myRow;
      Text {
        id: myText;
        text: 'Default';
        color: 'black';
        font.pixelSize: 12;
        font.family: "Tahoma";
      }  
    }
```

```
<div style="width: **37px**; height: 14px;">
  <div class="core-text" style="color: rgb(199, 199, 199); font-size: 12px; font-family: Tahoma; width: **38px**; height: 14px; padding-top: 0px;">Default</div>
</div>
```

**Comment by whoozle** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollWidth

>This property will round the value to an integer. If you need a fractional value, use element.getBoundingClientRect().

And we can't use getBoundingClientRect, it's not widely supported, and have issues with zooming, some browsers return zoomed values and this is not we probably want. 

If you need exact value, you can try getting it from element.fullWidth(), this will trigger proper async DOM update to the element, and trigger relayout.
