### ISSUE TITLE
Cannot directly reference the array data declared in the property

### ISSUE THREAD

**Issue by paiext** [pureqml/qmlcore#178]
Compiling the below codes generates the following error.

building app for web...
parsing src\app.qml ... src.app
src\app.qml:7:3: error: Expected "}", found 'R'  (at char 114), (line:7, col:3)
  Row {

```
Rectangle {
  id: root;
  width: 300;
  height: 300;   
  property array colors: ['red','green','blue'];      

  Row {
    id: row;
    spacing: 5;    
    Repeater {
      model: 3;      
      delegate: Rectangle {
        width: 100;
        height: 100;
        color: root.colors[model.index];
      }
    }
  }
}
```

**Comment by whoozle** [comment]
we did not reach any conculsion regarding this. it's relatively easy to add, but there's a few quite significant drawbacks to it

This gives one an impression that updating colors will trigger corresponding color updates, whilst it will not work properly. This definitely will lead to hard to catch bugs. 

I think we finally have to add this to grammar :)

**Comment by whoozle** [comment]
Please take a look, your example is functional now. 

Unfortunately due to the pyparsing limitation we can't support generic expr[expr] expression, it's only can be used as <rvalue nested id>[generic expression]. 

If you need anything else, just create a ticket or reopen this one
