### ISSUE TITLE
doubled object discard

### ISSUE THREAD

**Issue by vkrv** [pureqml/qmlcore#18]
There are many warnings like this when model data drops
invalid removeListener(boxChanged, function () { [native code] }) invocation Error
    at t.core.Text.t.core.EventEmitter.removeListener

**Comment by vkrv** [comment]
`failed to remove changed listener for XXX from YYY` happens upon removal of an object from a view, but only in those cases where properties' bindings declared in prototype, otherwise everything is ok

**Comment by whoozle** [comment]
we don't count double-added listeners, now it's not an issue, since it's safe to do so, and it's hidden. this logs will be shown only if trace.listeners was true
