### ISSUE TITLE
onHoverChanged bug

### ISSUE THREAD

**Issue by rei-kon** [pureqml/qmlcore#183]
Create TestObj.qml:
```
WebItem {
    id: testHover;
    width: 100;
    height: 100;
    color: "red";
    x: 200;
    z: 200;

    onHoverChanged: {
         if(value) {
            this.color = "blue"
         } else {
            this.color = "red"
         }
    }
}
```

Insert it in your app.qml code (sample 1):
```
TestObj {
    y: 200;
}

TestObj {
    y: 400;
}
```

In this case hover on testObj elements won't work.

But if you add hover watcher directly in app.qml for TestObj objects, hover starts work as expected.

```
TestObj {
    y: 200;

    onHoverChanged: {
         if(value) {
            this.color = "blue"
         } else {
            this.color = "red"
         }
    }
}

TestObj {
    y: 400;

    onHoverChanged: {
         if(value) {
            this.color = "blue"
         } else {
            this.color = "red"
         }
    }
}
``` 

But if we add hover condition in any testObj property, i.e.
```
WebItem {
    ...
    height: hover ? 100 : 100;
    ...
}
```
app.qml code in sample 1 starts work correct

**Comment by whoozle** [comment]
Very weird, it looks absolutely fine in inspector

![image](https://user-images.githubusercontent.com/480115/74448901-a6828a80-4e73-11ea-9806-71cf5cf2e2c4.png)

**Comment by whoozle** [comment]
and moreover callbacks are fired, so they are fine :)

**Comment by whoozle** [comment]
found a bug in alias property, which is preventing prototype callbacks from being called.
