### ISSUE TITLE
Encoding problem at compilation

### ISSUE THREAD

**Issue by paiext** [pureqml/qmlcore#186]
building app for web...
error: 'cp949' codec can't decode byte 0xe2 in position 655: illegal multibyte sequence

I solved that error by fixing line 57 of '__init__.py' as below.

before: with open(path) as f:
after: with open(path, encoding='utf-8') as f:

**Comment by whoozle** [comment]
I assume it's fixed in 875357b1ff20b5e4827fedde506d72883519eb0e, feel free to reopen it
