### ISSUE TITLE
Repeater Bug when model row removed

### ISSUE THREAD

**Issue by GuyInCorner** [pureqml/qmlcore#189]
If you remove an item from the model the Repeater leaves a gap where the removed one was.  This doesn't happen with the ListView.
As expected if you remove the last item from the model and then add another item, the Repeater still leaves a gap where the ListView does not.
I would have expected the ListView and Repeater to look the same in this case.

I've attached a simple app to reproduce.
[app-repeater.txt](https://github.com/pureqml/qmlcore/files/4629770/app-repeater.txt)

The following is a sample of the unexpected output :
<img width="190" alt="Screen Shot 2020-05-14 at 10 50 12 AM" src="https://user-images.githubusercontent.com/61481372/81962279-bf185300-95d0-11ea-87c8-321d1e59470a.png">

**Comment by whoozle** [comment]
That's really interesting finding and missing piece of functionality in Repeater, thanks!
