### ISSUE TITLE
Different delegates for QML ListView

### ISSUE THREAD

**Issue by maxiannunziata** [pureqml/qmlcore#196]
I would like to know if it's possible to use (several) different delegates for a QML ListView.

Depending on the individual object in the ListView model, I would like to visualize the objects with different delegates.

**Comment by whoozle** [comment]
Yes, it is possible. You can create root dispatcher item, e..g 

```qml
MyDelegate {
  type: model.type
  Text { text: model.text; visible: parent.type === 'text' }
  Button { text: model.text; visible: parent.type === 'button' }
}
```

This approach has a drawback though, it creates all elements, if it's not desirable, the alternative approach could be using `Loader`

// We include components on-demand, so you need to specify @using directive for each possible component to load.
//@using { myproject.delegate.Text }
//@using { myproject.delegate.Button }

```qml
Loader {
  source: 'myproject.delegate.' + model.component;
}
```
To specify root namespace you can use "package" property of the manifest. (or it would be `src`)

**Comment by maxiannunziata** [comment]
thank you!
