### ISSUE TITLE
Implement proper fix for scope lookup

### ISSUE THREAD

**Issue by whoozle** [pureqml/qmlcore#208]
Initial fix was delivered in #205

There's a few problem with that:
1. Using `w0` should trigger an exception regarding unknown property. 
2. (1) doesn't happen because find_property() returns property object (figure out why)
3. pass parent generator to property instance so we know property -> generator relation (and figure out relation from current component to the resolved property parent)
4. generate code not in transform, but in intermediate representation level, which is a bit higher level.

**Comment by tomager** [comment]
We're currently evaluating whether to use pureqml for a new project, so I may have more cycles for this soon.

For item 1, do you mean at compile time generate an error if `w0` is not visible even in parent scope(s)?

**Comment by whoozle** [comment]
>For item 1, do you mean at compile time generate an error if w0 is not visible even in parent scope(s)?

I mean that in your first example compiler should throw an error saying unknown property `w0` ! :) I checked find_property and it actually return lang.Property object (it means it found it somewhere)

**Comment by whoozle** [comment]
BTW I'm not saying that you have to do it :))
This is sort of tech debt issue for anyone interested in the future.

**Comment by tomager** [comment]
Yeah understood, but happy to if I have time and also it's a good way to learn.

It would be great to have tests for these sorts of changes. Do you have any thoughts on how to implement compiler tests? There don't seem to be any right now.

**Comment by whoozle** [comment]
Normally we check it on a few large projects we have. Recently we converted all dicts to OrderedDicts (I know that recent version of python do it by default, but we need python2 even though it's dead for a while :) ). So update could change only relatively small amount of js code generated and it's pretty much "diffable".

Unfortunately we don't have enough resources to extensively test and support compiler. We have some test for complex runtime stuff like model update optimiser, run by `npm test` in qmlcore directory and we have test application called [parus](https://github.com/pureqml/parus).

**Comment by whoozle** [comment]
2 looks like #172
