### ISSUE TITLE
Outermost Item not always resizing to context

### ISSUE THREAD

**Issue by tomager** [pureqml/qmlcore#209]
In Brave and Chrome (and likely Opera), I see a white line on the right hand side of the window when running the simple example below. It only appears sometimes (in Brave only after resizing the window, and in Chrome sometimes on startup as well). This issue doesn't exist (ie, the window is entirely blue) on Firefox and Edge.

Attached png and gif animation show the problem.

It feels like some kind of issue where the qml update is not called when the window stops resizing (possibly because update is still running from the last time width changed triggered update?).

```
Rectangle {
    anchors.fill: context;
    color: "blue";
}
```

![white line](https://user-images.githubusercontent.com/35665812/125020650-188ddd80-e02e-11eb-8b89-b0b59b86f0fb.png)

![white line](https://user-images.githubusercontent.com/35665812/125021185-fea0ca80-e02e-11eb-8852-7945faafa016.gif)

**Comment by whoozle** [comment]
Interesting, there's also small black artefacts (looks like area under mouse wasn't properly repainted) in your gif

what operating system are you using? Is it Xorg or Wayland?  is it hardware accelerated chrome? what GPU do you have? do you have any additional styles in your html file?

**Comment by whoozle** [comment]
I can't reproduce it using official chrome for Linux on my machine, Gentoo/Xorg/1050Ti
Version 91.0.4472.114 (Official Build) unknown (64-bit)

**Comment by tomager** [comment]
Both are Windows (mostly I do dev on linux server and Windows for desktop). Happens on two machines (both Windows), with integrated Intel and Nvidia graphics.

Brave: Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
Chrome: Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by tomager** [comment]
No, there is no extra styling anywhere. The html file is the one generated from the --boilderplate option.

**Comment by whoozle** [comment]
@tomager we had this feature request for a while (although privately). 

Instead of keeping full screen rectangle anchored maybe provide background/colour to the context itself. I think this may solve all kind of problems in different html engines. 
On other hand this will require adding it to native ports, but this shouldn't be a problem. 

Could you do a few tests for me please?
1. try do something like the following in the root item: 

```qml
onCompleted: {
  context.style('background-color', 'blue');
}
```
Then check chrome web inspector that style was actually applied and visible in tag with id `qml-context-index` and try resizing it. 

2. Try setting this attribute directly in chrome web inspector to the `<body>` tag to see if it's working. I assume this will fix it.

**Comment by whoozle** [comment]
Interesting, I think I managed to reproduce this issue after setting style on context div! 


Could you try 
```patch
--- a/platform/html5/html.js
+++ b/platform/html5/html.js
@@ -563,7 +563,7 @@ exports.init = function(ctx) {
        log("Context: window size: " + w + "x" + h);
        div = html.createElement(ctx, tag)
        div.dom.id = divId
-       win.on('resize', function() { ctx.width = win.width(); ctx.height = win.height(); });
+       win.on('resize', function() { ctx.width = win.width() + 1; ctx.height = win.height(); });
        var body = html.getElement(ctx, 'body')
        body.append(div);
    }
```

**Comment by tomager** [comment]
Super-- that fixes it for me. Submitted a pull request that does the height and init cases as well.
