### ISSUE TITLE
error: No module named jinja2

### ISSUE THREAD

**Issue by maxiannunziata** [pureqml/qmlcore#219]
> anz@MacBook-Pro-de-Maximiliano`x-smarttv % ./qmlcore/build -p web         
>
>building app for web...
>parsing ./qmlcore/core/Device 2.qml ... core.Device 2
>parsing ./qmlcore/core/Gamepad 2.qml ... core.Gamepad 2
>parsing ./qmlcore/core/Text 2.qml ... core.Text 2
>parsing ./qmlcore/core/EventEmitter 2.qml ... core.EventEmitter 2
>parsing ./qmlcore/core/GridView 2.qml ... core.GridView 2
>parsing ./qmlcore/core/Radius 2.qml ... core.Radius 2
>parsing ./qmlcore/core/Context 2.qml ... core.Context 2
>parsing ./qmlcore/core/Transform 2.qml ... core.Transform 2
>parsing ./qmlcore/core/ProxyModel 2.qml ... core.ProxyModel 2
>parsing ./qmlcore/core/ListView 2.qml ... core.ListView 2
>parsing ./qmlcore/core/Item 2.qml ... core.Item 2
>parsing ./qmlcore/core/Timer 2.qml ... core.Timer 2
>parsing ./qmlcore/core/Image 2.qml ... core.Image 2
>parsing ./qmlcore/core/MouseArea 2.qml ... core.MouseArea 2
>parsing ./qmlcore/core/ColorAnimation 2.qml ... core.ColorAnimation 2
>done
>error: No module named jinja2

i tried build my project and get this error.
Where are located the directory that access to install the jinja2 module ?

**Comment by maxiannunziata** [comment]
i changed the build file

from: 

`#!/usr/bin/env **python**

from __future__ import print_function
from future import standard_library
from future.utils import PY2
standard_library.install_aliases()
from builtins import filter, range

from compiler import manifest as mf
from compiler import compile_qml

`

to 

`#!/usr/bin/env **python3**

from __future__ import print_function
from future import standard_library
from future.utils import PY2
standard_library.install_aliases()
from builtins import filter, range

from compiler import manifest as mf
from compiler import compile_qml

`

and works

**Comment by whoozle** [comment]
you can also try `pip install jinja2`.  pureqml should work fine in python-2/3 environments
`!/usr/bin/env python` will run default python (2.x on macosx)
