### ISSUE TITLE
Multi-line text

### ISSUE THREAD

**Issue by comrat** [pureqml/qmlcore#23]
We must concatinate every line right now to write multi-line strings property values. It will be cool to write it like this:
text: "
   foo
   bar
";

**Comment by whoozle** [comment]
it's been like this forever, just added multiline test to check it in a few places similar to code below 
```
-                       GradientStop { position: 0; color: "red";}
+                       GradientStop { position: 0; color: "red
+                       2
+                       3
+                       4";}
```
