### ISSUE TITLE
Android to desktop or web

### ISSUE THREAD

**Issue by AceKiron** [pureqml/qmlcore#235]
There's this Android app built with PureQML that I feel like should have a Desktop or Web version, but it doesn't. Are there any tools to convert from the Android version to Desktop or Web? If not, are such features planned?

**Comment by whoozle** [comment]
No we don't, although with a bit of luck you can probably transplant generated code into web qml app. 
Native android app has qml.xxx.js resource file similar to what web app would have. 

On other hand you can't update an app this way or tweak it to accomodate web UX. I'd recommend asking app author to release this app for web. (this is easy, they can just compile it with `build -p web` from the same sources they have for android)
