### ISSUE TITLE
I ask you how you can define an object-type variable with property?

### ISSUE THREAD

**Issue by numaelis** [pureqml/qmlcore#239]
I congratulate you for an excellent project!
Thank you for doing this!
I ask you how you can define an object-type variable with property?
example:
  property var myobject: {"name":"Jose"};

**Comment by whoozle** [comment]
after 777da4d9f54d6fb75df958a26b82d9f8ccd3e7fb you can do `property var myobject: {"name":"Jose"};` 
but values there should be JSON-like object, no dynamic properties supported yet. 

E.g. currently it's impossible to do : 
```
property int test;
property var test2 : { value: test } 
```

**Comment by whoozle** [comment]
on other hand I realised how to do it.

Dependencies should work in object values:
```
property int test;
property var test2 : { value: test } 
```

after  b11a5551651a821910c818ffe6357b745dd2d47b

feel free to reopen/submit any new issues you might have
