### ISSUE TITLE
htmlTag always returns 'div'

### ISSUE THREAD

**Issue by madagon** [pureqml/qmlcore#244]
Setting `htmlTag` on a component has no effect on its construction. Within the `Item.qml`' constructor, calling `htmlTag()` always returns `div`. Apparently, the properties are not processed and attached to `this` before the instantiation.

All web controls are affected. 
A temporary workaround would be overriding the getTag() function in each component.

```
Script {
    source: 'http://cdn...';

    function getTag() {
        return 'script';
    }
}
```

**Comment by whoozle** [comment]
sorry, unfortunate refactoring, this is impossible to do without "static" prototype properties.
Should be fixed after the following reverts
48c15abffd755f364c50e103dfd4098ace353059 
39a28c740265cd6e66075c688e91f0ea8d9c2a81
