### ISSUE TITLE
Question & Suggestion ?

### ISSUE THREAD

**Issue by jhay06** [pureqml/qmlcore#246]
Hi would like to ask and suggest 

, can we remove at the future the needed semicolon ? 

and does it support a module or custom module / qmldir

**Comment by whoozle** [comment]
duplicate of #86 

could you create a new ticket with module/custom module/qmldir and describe it in more detail what you need

our transpiler is processing all directories which have manifest in them. take a look at directory structure of pureOSD project at 
https://github.com/pureqml/pureosd
