### ISSUE TITLE
peculiar statements doesn't work in declarations

### ISSUE THREAD

**Issue by vkrv** [pureqml/qmlcore#26]
Here is a couple of examples I found:
Text { text: (123.456).toFixed(2); }
//won't compile

Text { 
text: radius.toFixed(2);
}
//Cannot read property 'toFixed' of undefined in runtime

**Comment by whoozle** [comment]
what's radius in this example? any property?

**Comment by whoozle** [comment]
looks like declaring function_call as ```expression + Literal("(").suppress() + Optional(expression_list) + Literal(")").suppress() + ZeroOrMore(Literal(".").suppress() + Literal("arg").suppress() + Literal("(").suppress() + expression + Literal(")").suppress())```
causes recursion depth exception. :(

probably unfixable until new parser came in

**Comment by whoozle** [comment]
Fixed in feb515c7454510abd6212ed45ced3b5e4ead32e5
