### ISSUE TITLE
Generalize VideoPlayer code

### ISSUE THREAD

**Issue by comrat** [pureqml/qmlcore#53]

**Comment by whoozle** [comment]
1. Leave only one VideoPlayer facade implementation
2. Provide backend string property with some platform-specific default, "auto", allow fallbacks in case playback fails, e.g. "html5": ["hlsjs", "video"]
3. Specify api for video player backends

**Comment by whoozle** [comment]
current code in https://github.com/pureqml/qmlcore/tree/video-player-refactoring

**Comment by comrat** [comment]
Merged in master 926df9503735181eb10a3e677b8e1ab129a9ba7f
