### ISSUE TITLE
hybrid usage of translateX/Y and contentX/Y in Views

### ISSUE THREAD

**Issue by vkrv** [pureqml/qmlcore#8]
if particular platform supports HW-acceleration use translateX/Y instead of left/top

**Comment by whoozle** [comment]
why views only? any item can be animated and moved around

**Comment by vkrv** [comment]
views are isolated enough and their content generally moves on either X- or Y-axis, so transition on transform won't affect wrong axis. Besides desired items behavior and translate positioning can be achieved with transform property directly.

**Comment by whoozle** [comment]
added in 5153cc664d43a16e30195dae710abbdbab17f8b9
