### ISSUE TITLE
Rectangle color transition is not working

### ISSUE THREAD

**Issue by whoozle** [pureqml/qmlcore#82]
Animation sets on 'color', instead of 'background-color'

**Comment by vkrv** [comment]
I believe we have 3 options here:
- rename either of the properties to textColor or backgroundColor or whatever and add the mapping accordingly(looks a bit ugly for me);
- do some magic and consider the type of element where behavior declared(sort of ambiguity in the long run);
- use behavior on background to do the trick and keep it as it is.

background isn't the only indirect mapping we have, font and transform provide similar though aggregated mapping as well. My fave is the third.

**Comment by whoozle** [comment]
Hybrid of 2nd and 3rd option: provide hint from element, hence transition operates on css level and we have to provide some mapping layer already. I was thinking about moving mappings api into Element prototype and allow fixups there

**Comment by whoozle** [comment]
fixed in d968a96f1ff69631933093be8ba4d8f2409cdab8
