### ISSUE TITLE
'title' attribute

### ISSUE THREAD

**Issue by comrat** [pureqml/qmlcore#85]
If you declare property with 'title' name (property string title;) corresponded div will have 'title' attribute

**Comment by whoozle** [comment]
can't reproduce on the latest master/controls

**Comment by whoozle** [comment]
what exact component did you use?

**Comment by comrat** [comment]
Item {
	anchors.fill: parent;

	ListView {
		width: 200;
		height: 100%;
		spacing: 10;
		delegate: WebItem {
			property string title: model.title;
			width: 200;
			height: 200;
			color: "red";
		}
		model: ListModel {
			ListElement { title: "foo"; }
			ListElement { title: "bar"; }
			ListElement { title: "baz"; }
		}
	}
}

**Comment by whoozle** [comment]
# delegate: WebItem

**Comment by whoozle** [comment]
```
	/// @private
	onTitleChanged: { this.element.dom.setAttribute('title', value); }
```
this is exactly what WebItem.qml code does. setting attribute 'title'. The thing is why it's working and not detected by compiler.

**Comment by comrat** [comment]
LOL
Maybe we should remove this line and create special mixin for such purpose
TitleMixin I guess

**Comment by comrat** [comment]
Fixed in [controls](https://github.com/pureqml/controls) repo
[982ba7a65e1414324242a960fadd2eadb65909b2](https://github.com/pureqml/controls/commit/982ba7a65e1414324242a960fadd2eadb65909b2)
