### ISSUE TITLE
Device backend

### ISSUE THREAD

**Issue by comrat** [pureqml/qmlcore#88]
Reimplement Device.qml using platform backends

**Comment by whoozle** [comment]
Please remove location copies from platforms too. This is very similar situation. Differences between Location objects are very subtle and mostly it's a native platform events subscription & initialisation. Backend is a good place to do it.

**Comment by comrat** [comment]
Done [4d303eb4f61f4ae41fdb1299e8c14475adcb6683](https://github.com/pureqml/qmlcore/commit/4d303eb4f61f4ae41fdb1299e8c14475adcb6683)
