### ISSUE TITLE
Как запустить build? 

### ISSUE THREAD

**Issue by MASTER-OF-ORION** [pureqml/qmlcore#89]
Это простой файл без расширения, чем его запускать-то? Питоном что ли? Как?
P.S.: Речь про винду :-)

Запустил питоном (это ж надо было на питоне написать :-D ), но ребят, там ошибки:
http://i101.fastpic.ru/big/2017/1231/a9/def3f5c32a2971683c9cd39cf68ed9a9.png

**Comment by whoozle** [comment]
Мы не поддерживаем windows в качестве платформы разработки. А ошибки у вас, потому что наш компилятор написан под python2, см. shebang в начале файлов. 

Не думаю, что тут уместно обсуждать наши способы разработки, или среды исполнения, на всё есть свои причины. 

До свидания, всего хорошего.

**Comment by MASTER-OF-ORION** [comment]
Владимир, да я не хотел вас обидеть, ни в коем разе , вы что :-) То, что
питон - редкостное.... г... это лишь моё субъективное мнение. Но самом деле
ваш проект интересен, я его уже протестировал, но к сожалению, вы вводите
какие-то своих фишки QML, не существующие в оригинале, в общем... Лучше,
либо придерживаться того, что есть, либо ждать, пока браузеры сделают QML
вместо HTML

2018-01-01 15:57 GMT+03:00 Vladimir <notifications@github.com>:
