### ISSUE TITLE
Qt Creator

### ISSUE THREAD

**Issue by ShalokShalom** [pureqml/qmlcore#91]
Is there any support (planned) in order to create UI`s with the Qt Quick Creator?

**Comment by whoozle** [comment]
Is there anything specific you have in mind? You can edit pureqml qml files in Qt Creator, but they most likely won't work in Qt, except trivial examples. 
 
we're not aiming to be 100% compatible, there's some progress on removing strict semicolon rules from grammar, but not much above it.

**Comment by ShalokShalom** [comment]
See here: http://doc.qt.io/qtcreator/creator-using-qt-quick-designer.html

**Comment by whoozle** [comment]
Fixing #118 is the most I could do unfortunately. Our dialect is not really compatible with Qt Quick in many aspects, sorry about that.
