### ISSUE TITLE
Description of the project in Github 

### ISSUE THREAD

**Issue by ShalokShalom** [pureqml/qmlcore#93]
Qmlcore is here described as "QML to HTML5 translator" and it translates also in CSS and JS, yes?

**Comment by whoozle** [comment]
in fact generated code is mostly in javascript, index.html is just a simple launcher :)

**Comment by ShalokShalom** [comment]
In fact, HTML is what the description says right now. So who like to change it?

**Comment by whoozle** [comment]
> QML to Javascript/HTML5 translator, both for mobile and desktop targets
how does it sound?

**Comment by ShalokShalom** [comment]
Just out of curiosity and since you seem to be a native speaker: 
Is "QML to Javascript/HTML5 translator for both, mobile and desktop targets" also correct?

**Comment by whoozle** [comment]
I'm no native speaker, sorry, my first language is russian. :)

**Comment by ShalokShalom** [comment]
OK, fine. I think both are correct :)

**Comment by whoozle** [comment]
thanks for your feedback!
